import { useEffect, useState } from 'react';
import axios from '../../api/axios';
import { useAuth } from '../../context/AuthContext';
import { DollarSign, X , Download} from 'lucide-react';
import { useMounted, fadeUp, fadeIn } from '../../hooks/useAnimation';
import toast from 'react-hot-toast';

export default function EmployeePayroll() {
  const { user } = useAuth();
  const mounted = useMounted();
  const [payrolls, setPayrolls] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    const fetchPayrolls = async () => {
      if (!user?.employeeId) { setLoading(false); return; }
      try {
        const res = await axios.get(`/payroll/my/${user.employeeId}`);
        setPayrolls(res.data);
      } catch (err) {
        console.log(err);
      } finally {
        setLoading(false);
      }
    };
    fetchPayrolls();
  }, [user]);

  const latestPaid = payrolls.find(p => p.status === 'paid');
  const totalEarned = payrolls
    .filter(p => p.status === 'paid')
    .reduce((acc, p) => acc + (p.netSalary || 0), 0);

    const handleDownloadSlip = async (payroll) => {
  try {
    const res = await axios.get(`/payroll/${payroll._id}/slip`, {
      responseType: 'blob'
    });
    const url = window.URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Payslip_${payroll.month}_${payroll.year}.pdf`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
    toast.success('Payslip downloaded!');
  } catch (err) {
    toast.error('Failed to download payslip');
  }
};


  if (loading) return (
    <div className="flex items-center justify-center h-96">
      <div className="w-10 h-10 border-4 border-emerald-400 border-t-transparent rounded-full animate-spin"></div>
    </div>
  );

  return (
    <div style={fadeIn(mounted)}>
      <div className="mb-8" style={fadeUp(mounted, 100)}>
        <h1 className="text-3xl font-bold text-white">My Payroll</h1>
        <p className="text-slate-400 mt-1">View your salary slips and payment history</p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-5 mb-8" style={fadeUp(mounted, 200)}>
        <div className="rounded-2xl p-6 border border-emerald-500 border-opacity-20"
          style={{ background: 'rgba(16,185,129,0.05)' }}>
          <p className="text-slate-400 text-sm mb-1">Latest Net Salary</p>
          <p className="text-3xl font-bold text-emerald-400">
            {latestPaid ? `Rs.${latestPaid.netSalary?.toLocaleString()}` : '—'}
          </p>
          {latestPaid && (
            <p className="text-xs text-slate-500 mt-1">{latestPaid.month} {latestPaid.year}</p>
          )}
        </div>
        <div className="rounded-2xl p-6 border border-slate-800"
          style={{ background: '#111827' }}>
          <p className="text-slate-400 text-sm mb-1">Total Slips</p>
          <p className="text-3xl font-bold text-amber-400">{payrolls.length}</p>
          <p className="text-xs text-slate-500 mt-1">All time</p>
        </div>
        <div className="rounded-2xl p-6 border border-slate-800"
          style={{ background: '#111827' }}>
          <p className="text-slate-400 text-sm mb-1">Total Earned</p>
          <p className="text-3xl font-bold text-purple-400">
            Rs.{totalEarned.toLocaleString()}
          </p>
          <p className="text-xs text-slate-500 mt-1">Paid slips only</p>
        </div>
      </div>

      {/* Payroll Cards */}
      {payrolls.length === 0 ? (
        <div className="rounded-2xl p-12 text-center border border-slate-800"
          style={{ background: '#111827', ...fadeUp(mounted, 300) }}>
          <DollarSign size={48} className="text-slate-700 mx-auto mb-4" />
          <p className="text-slate-500">No payroll records yet</p>
          <p className="text-slate-600 text-sm mt-1">Your salary slips will appear here once generated by admin</p>
        </div>
      ) : (
        <div className="grid grid-cols-2 gap-5" style={fadeUp(mounted, 300)}>
          {payrolls.map((payroll, i) => (
            <div key={payroll._id}
              onClick={() => setSelected(payroll)}
              className="rounded-2xl p-6 border border-slate-800 hover:border-emerald-500 hover:border-opacity-50 transition cursor-pointer hover:-translate-y-1 hover:shadow-xl"
              style={{ background: '#111827' }}>

              <div className="flex justify-between items-start mb-4">
                <div>
                  <h3 className="font-bold text-white text-lg">{payroll.month} {payroll.year}</h3>
                  <span className={`text-xs px-2 py-1 rounded-full font-medium mt-1 inline-block ${
                    payroll.status === 'paid'
                      ? 'bg-green-400 bg-opacity-10 text-green-400'
                      : 'bg-yellow-400 bg-opacity-10 text-yellow-400'
                  }`}>
                    {payroll.status === 'paid' ? '✓ Paid' : '⏳ Pending'}
                  </span>
                </div>
                <DollarSign size={24} className="text-emerald-400 opacity-40" />
              </div>

              <div className="space-y-2 mb-4">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Basic Salary</span>
                  <span className="text-white">Rs.{payroll.basicSalary?.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Total Allowances</span>
                  <span className="text-emerald-400">
                    +Rs.{(payroll.grossSalary - payroll.basicSalary)?.toLocaleString()}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Total Deductions</span>
                  <span className="text-red-400">-Rs.{payroll.totalDeductions?.toLocaleString()}</span>
                </div>
              </div>

              <div className="flex justify-between pt-3 border-t border-slate-800">
                <span className="text-white font-semibold">Net Salary</span>
                <span className="text-emerald-400 font-bold text-xl">
                  Rs.{payroll.netSalary?.toLocaleString()}
                </span>
              </div>

              <p className="text-xs text-slate-600 mt-3 text-center">
                Click to view full salary slip
              </p>
            </div>
          ))}
        </div>
      )}

      {/* Salary Slip Modal */}
      {selected && (
        <div className="fixed inset-0 bg-black bg-opacity-70 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="rounded-2xl p-8 w-full max-w-md border border-slate-800 max-h-[90vh] overflow-y-auto"
            style={{ background: '#0d1426' }}>
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold text-white">Salary Slip</h2>
              <div className="flex items-center gap-2">
                <button onClick={() => handleDownloadSlip(selected)}
                className="p-2 text-emerald-400 hover:bg-emerald-400 hover:bg-opacity-10 rounded-lg transition">
                <Download size={18} />
               </button>
              <button onClick={() => setSelected(null)}
                className="p-2 text-slate-500 hover:text-white hover:bg-slate-800 rounded-lg">
                <X size={20} />
              </button>
            </div>
           </div>
             
            {/* Employee Info */}
            <div className="p-4 rounded-xl border border-emerald-500 border-opacity-20 mb-6"
              style={{ background: 'rgba(16,185,129,0.05)' }}>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-bold text-white text-lg">{selected.month} {selected.year}</p>
                  <p className="text-slate-500 text-sm">Pay Period</p>
                </div>
                <span className={`text-xs px-3 py-1.5 rounded-full font-medium ${
                  selected.status === 'paid'
                    ? 'bg-green-400 bg-opacity-10 text-green-400'
                    : 'bg-yellow-400 bg-opacity-10 text-yellow-400'
                }`}>
                  {selected.status === 'paid' ? '✓ Paid' : '⏳ Pending'}
                </span>
              </div>
            </div>

            {/* Earnings */}
            <div className="space-y-1">
              <p className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-3">
                Earnings
              </p>
              {[
                { label: 'Basic Salary', value: selected.basicSalary, pct: null },
                { label: 'HRA', value: selected.allowances?.hra, pct: selected.percentages?.hra },
                { label: 'DA (Dearness Allowance)', value: selected.allowances?.da, pct: selected.percentages?.da },
                { label: 'TA (Travel Allowance)', value: selected.allowances?.ta, pct: selected.percentages?.ta },
                { label: 'Medical Allowance', value: selected.allowances?.medical, pct: selected.percentages?.medical },
              ].map((item, i) => (
                <div key={i} className="flex justify-between items-center py-2 border-b border-slate-800">
                  <div>
                    <span className="text-slate-300 text-sm">{item.label}</span>
                    {item.pct !== null && item.pct !== undefined && (
                      <span className="text-xs text-slate-600 ml-2">({item.pct}%)</span>
                    )}
                  </div>
                  <span className="text-white text-sm font-medium">
                    Rs.{item.value?.toLocaleString()}
                  </span>
                </div>
              ))}

              <div className="flex justify-between items-center py-3 font-bold border-b-2 border-slate-700">
                <span className="text-white">Gross Salary</span>
                <span className="text-white text-lg">Rs.{selected.grossSalary?.toLocaleString()}</span>
              </div>

              {/* Deductions */}
              <p className="text-xs font-semibold text-red-400 uppercase tracking-wider mb-3 mt-5">
                Deductions
              </p>
              {[
                { label: 'Provident Fund (PF)', value: selected.deductions?.pf, pct: selected.percentages?.pf },
                { label: 'Income Tax', value: selected.deductions?.incomeTax, pct: selected.percentages?.incomeTax },
                { label: 'Professional Tax', value: selected.deductions?.professionalTax, pct: selected.percentages?.professionalTax },
                { label: 'ESI', value: selected.deductions?.esi, pct: selected.percentages?.esi },
              ].map((item, i) => (
                <div key={i} className="flex justify-between items-center py-2 border-b border-slate-800">
                  <div>
                    <span className="text-slate-300 text-sm">{item.label}</span>
                    {item.pct !== null && item.pct !== undefined && (
                      <span className="text-xs text-slate-600 ml-2">({item.pct}%)</span>
                    )}
                  </div>
                  <span className="text-red-400 text-sm font-medium">
                    -Rs.{item.value?.toLocaleString()}
                  </span>
                </div>
              ))}

              <div className="flex justify-between items-center py-3 border-b-2 border-slate-700 font-bold">
                <span className="text-white">Total Deductions</span>
                <span className="text-red-400 text-lg">-Rs.{selected.totalDeductions?.toLocaleString()}</span>
              </div>

              {/* Net Salary */}
              <div className="flex justify-between items-center py-5 mt-2 rounded-xl px-4"
                style={{ background: 'rgba(16,185,129,0.05)', border: '1px solid rgba(16,185,129,0.2)' }}>
                <span className="text-white font-bold text-xl">Net Salary</span>
                <span className="text-emerald-400 font-bold text-3xl">
                  Rs.{selected.netSalary?.toLocaleString()}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}